# Generated by Django 5.2.17 on 2026-09-18 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField()),
                ('par', models.IntegerField(default=4)),
                # Final name (was briefly 'index' in older deployments)
                ('handicap_index', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['hole_number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handicap', models.IntegerField(default=0)),
                ('member_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GolfRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(default='PRGC Course', max_length=200)),
                ('active_players', models.ManyToManyField(related_name='rounds', to='scorecard.player')),
            ],
        ),
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Final names (were briefly strokes/points in older deployments)
                ('net_value', models.IntegerField(default=0)),
                ('gross_value', models.IntegerField(default=0)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='scorecard.hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scorecard.golfround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_scores', to='scorecard.player')),
            ],
            options={
                'unique_together': {('round', 'player', 'hole')},
            },
        ),
    ]
