# Generated by Django 5.2.17 on 2026-09-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('course_cut_per_player', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('specialty_pot_percentage', models.IntegerField(default=10, help_text='Percentage of remainder for Skins/KP')),
                ('skins_split_percentage', models.IntegerField(default=50)),
                ('kp_split_percentage', models.IntegerField(default=50)),
                ('skins_winners', models.CharField(blank=True, default='', help_text="Enter names or 'No skins won'", max_length=255)),
                ('kp_winners', models.CharField(blank=True, default='', help_text='Enter names of closest to the hole winners', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='hole',
            old_name='index',
            new_name='handicap_index',
        ),
        migrations.RenameField(
            model_name='holescore',
            old_name='points',
            new_name='gross_value',
        ),
        migrations.RenameField(
            model_name='holescore',
            old_name='strokes',
            new_name='net_value',
        ),
        migrations.RemoveField(
            model_name='golfround',
            name='active_players',
        ),
        migrations.AddField(
            model_name='golfround',
            name='game_format',
            field=models.CharField(choices=[('18_GROSS_NET', '18-Hole Individual Gross/Net'), ('18_IND_CHICAGO', '18-Hole Individual Chicago Points'), ('9_TEAM_CHICAGO', '9-Hole Team Chicago Points'), ('9_WOMENS_LEAGUE', "9-Hole Women's League"), ('9_HOLE_SCRAMBLE', 'Scramble Tournament (9 Holes)')], default='18_GROSS_NET', max_length=30),
        ),
        migrations.AddField(
            model_name='golfround',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chicago_points_18',
            field=models.IntegerField(default=0, verbose_name='18 Hole Chicago Quota'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Team Captain'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_playing_today',
            field=models.BooleanField(default=False, verbose_name='Playing Today'),
        ),
        migrations.AddField(
            model_name='player',
            name='ladies_league_handicap',
            field=models.IntegerField(default=0, verbose_name='Ladies League Handicap'),
        ),
        migrations.AddField(
            model_name='player',
            name='new_handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='riding_partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_mate', to='scorecard.player', verbose_name='Riding Partner (Same Cart)'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_chicago_points_9',
            field=models.IntegerField(default=0, verbose_name='9 Hole Team Chicago Quota'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='golfround',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='holescore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_number', models.IntegerField()),
                ('players', models.ManyToManyField(related_name='squads', to='scorecard.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='scorecard.golfround')),
                ('scorekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_squads', to='scorecard.player')),
                ('starting_hole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_squads', to='scorecard.hole')),
            ],
        ),
    ]
