# Generated by Django 5.2.17 on 2026-09-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_payoutsetting_rename_index_hole_handicap_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='riding_partner',
        ),
    ]
