# Generated by Django 5.2.17 on 2026-09-25 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_remove_player_riding_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='riding_partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_mate', to='scorecard.player', verbose_name='Riding Partner (Same Cart)'),
        ),
    ]
