# Generated by Django 5.2.17 on 2026-09-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_player_riding_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfround',
            name='metrics_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
