# Generated by Django 5.0.2 on 2024-02-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('memberid', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('firstname', models.CharField(max_length=45, verbose_name='First Name:')),
                ('lastname', models.CharField(max_length=45, verbose_name='Last Name:')),
                ('handicap', models.IntegerField(blank=True, default=None, null=True, verbose_name='Handicap')),
                ('username', models.CharField(max_length=45, verbose_name='User Name:')),
                ('password', models.CharField(blank=True, max_length=45, verbose_name='Password')),
                ('securitylevel', models.IntegerField(blank=True, default=None, null=True, verbose_name='Security Level')),
            ],
        ),
    ]
