# Generated by Django 5.2.1 on 2026-09-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0002_assignmentholes_finalscore_finalscorepayout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='start1hole9player4',
            old_name='bo44',
            new_name='box44',
        ),
    ]
