# Generated by Django 5.2.1 on 2026-09-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0003_rename_bo44_start1hole9player4_box44'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Grouptwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
    ]
