# Generated by Django 5.2.1 on 2026-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0004_groupone_grouptwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Groupfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Groupfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Groupnine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Groupseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Groupsix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
        migrations.CreateModel(
            name='Groupthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Member ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='First Name:')),
                ('lastname', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Last Name:')),
            ],
        ),
    ]
