# Generated by Django 5.2.1 on 2026-09-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0006_remove_start1hole2player1_box6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='start3hole3player1',
            name='box11',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start3hole3player2',
            name='box12',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start3hole3player3',
            name='box13',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start3hole3player4',
            name='box14',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start3hole3player5',
            name='box15',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
