# Generated by Django 5.2.1 on 2026-09-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0007_start3hole3player1_box11_start3hole3player2_box12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='start4hole4player1',
            name='box16',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start4hole4player2',
            name='box17',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start4hole4player3',
            name='box18',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start4hole4player4',
            name='box19',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start4hole4player5',
            name='box20',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
