# Generated by Django 5.2.1 on 2026-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0008_start4hole4player1_box16_start4hole4player2_box17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='start5hole5player1',
            name='box21',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start5hole5player2',
            name='box22',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start5hole5player3',
            name='box23',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start5hole5player4',
            name='box24',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start5hole5player5',
            name='box25',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
