# Generated by Django 5.2.1 on 2026-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0009_start5hole5player1_box21_start5hole5player2_box22_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='start6hole6player1',
            name='box26',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start6hole6player2',
            name='box27',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start6hole6player3',
            name='box28',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start6hole6player4',
            name='box29',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start6hole6player5',
            name='box30',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start7hole7player1',
            name='box31',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start7hole7player2',
            name='box32',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start7hole7player3',
            name='box33',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start7hole7player4',
            name='box34',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start7hole7player5',
            name='box35',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start8hole8player1',
            name='box36',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start8hole8player2',
            name='box37',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start8hole8player3',
            name='box38',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start8hole8player4',
            name='box39',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start8hole8player5',
            name='box40',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start9hole9player1',
            name='box41',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start9hole9player2',
            name='box42',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start9hole9player3',
            name='box43',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start9hole9player4',
            name='box44',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='start9hole9player5',
            name='box45',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
