# Generated by Django 5.2.1 on 2026-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0010_start6hole6player1_box26_start6hole6player2_box27_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicagoPts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts1', models.IntegerField(blank=True, default=None, null=True)),
                ('pts2', models.IntegerField(blank=True, default=None, null=True)),
                ('pts3', models.IntegerField(blank=True, default=None, null=True)),
                ('pts4', models.IntegerField(blank=True, default=None, null=True)),
                ('pts5', models.IntegerField(blank=True, default=None, null=True)),
                ('pts6', models.IntegerField(blank=True, default=None, null=True)),
                ('pts7', models.IntegerField(blank=True, default=None, null=True)),
                ('pts8', models.IntegerField(blank=True, default=None, null=True)),
                ('pts9', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
