# Generated by Django 5.2.1 on 2026-09-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0011_chicagopts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts2',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts3',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts4',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts5',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts6',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts7',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts8',
        ),
        migrations.RemoveField(
            model_name='chicagopts',
            name='pts9',
        ),
    ]
