# Generated by Django 5.2.1 on 2026-09-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0012_remove_chicagopts_pts2_remove_chicagopts_pts3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChicagoPts',
            new_name='ChicagoPts1',
        ),
    ]
