# Generated by Django 5.2.1 on 2026-09-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0014_chicagopts2_chicagopts3_chicagopts4_chicagopts5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicagopts1',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
