# Generated by Django 5.2.1 on 2026-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0015_chicagopts1_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start1hole1player1',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
