# Generated by Django 5.2.1 on 2026-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0016_alter_start1hole1player1_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='start1hole1player1',
            name='game',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='start1hole1player1',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Game ID'),
        ),
    ]
