# Generated by Django 5.2.1 on 2026-09-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0017_start1hole1player1_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='start1hole1player1',
            old_name='game',
            new_name='game1',
        ),
    ]
