# Generated by Django 5.2.1 on 2026-09-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0018_rename_game_start1hole1player1_game1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start1hole1player1',
            name='game1',
        ),
    ]
