# Generated by Django 5.2.1 on 2026-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRGCdatabase', '0019_remove_start1hole1player1_game1'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicagopts2',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts3',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts4',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts5',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts6',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts7',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts8',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chicagopts9',
            name='gameid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
